version: "3.8"
 
services:
  postgres:
    image: postgres:latest
    container_name: bookstore-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bansi123
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  catalog:
    build: ./catalog
    container_name: catalog-service
    restart: always
    environment:
      DATABASE_URL: postgresql://bookstore:bookstore@20.254.69.11:5432/bookstore_db
    ports:
      - "5001:5001"
    depends_on:
      - postgres
 
  cart:
    build: ./cart
    container_name: cart-service
    restart: always
    environment:
      CART_DATABASE_URL: postgresql://bookstore:bookstore@20.254.69.11:5432/bookstore_db
    ports:
      - "5002:5002"
    depends_on:
      - postgres
 
  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - catalog
      - cart
 
volumes:
  postgres_data: