apiVersion: batch/v1
kind: CronJob
metadata:
  name: restore-postgres-cron
  namespace: velero
spec:
  schedule: "*/1 * * * *"  # Runs every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: restore-postgres
            image: velero/velero:v1.10.2
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "🔍 Checking if PostgreSQL PVC is missing..."
                PVC_STATUS=$(kubectl get pvc postgres-pvc -o jsonpath='{.status.phase}' || echo "NotFound")
 
                if [[ "$PVC_STATUS" == "NotFound" ]]; then
                  echo "🚨 PostgreSQL PVC is missing! Restoring from Velero Backup..."

                  LATEST_BACKUP=$(velero backup get --output=json | jq -r '.items[] | select(.status.phase=="Completed") | .metadata.name' | tail -n 1)
 
                  if [[ -n "$LATEST_BACKUP" ]]; then
                    velero restore create --from-backup "$LATEST_BACKUP"
                    echo "✅ Restore triggered from backup: $LATEST_BACKUP"
                  else
                    echo "❌ No completed backup found! Skipping restore."
                    exit 1
                  fi
                else
                  echo "✅ PostgreSQL PVC exists. No restore needed."
                fi