apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "REACT_APP_CATALOG_SERVICE_API_URL": "http://bookstoreuniversityproject.duckdns.org/catalog-api",
      "REACT_APP_CART_SERVICE_API_URL": "http://bookstoreuniversityproject.duckdns.org/cart-api"
    }
