apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: teufelz/bookstore-cart:latest
        ports:
        - containerPort: 5002
        env:
        - name: CART_DATABASE_URL
          value: postgresql://admin:admin@postgres:5432/bookstore_db
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 5002
            host: cart-service
          initialDelaySeconds: 15 
          periodSeconds: 10 
          failureThreshold: 3 
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 5002
            host: cart-service
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
