apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: teufelz/bookstore-catalog:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: postgresql://admin:admin@postgres:5432/bookstore_db
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 5001
            host: catalog-service
          initialDelaySeconds: 15 
          periodSeconds: 10 
          failureThreshold: 3 
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 5001
            host: catalog-service
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
