apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: teufelz/bookstore-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_CATALOG_SERVICE_API_URL
          value: http://bookstoreuniversityproject.duckdns.org/catalog-api
        - name: REACT_APP_CART_SERVICE_API_URL
          value: http://bookstoreuniversityproject.duckdns.org/cart-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
