apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: default  # Update this if your frontend is in a different namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Optional: to rewrite the URL path
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend  # Replace with the name of your frontend service
            port:
              number: 80  # Replace with the port your frontend service is listening on
