apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    AZURE_SUBSCRIPTION_ID=80fc4c3b-7b5b-492b-8ded-388056106473
    AZURE_RESOURCE_GROUP=bookstore-rg
    AZURE_STORAGE_ACCOUNT=bookstorevelerobckpgp7