apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    app: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: velero
      containers:
        - name: velero
          image: velero/velero:v1.11.0
          args:
            - server
          volumeMounts:
            - mountPath: /credentials
              name: cloud-credentials
              readOnly: true
      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
---
apiVersion: v1
kind: Service
metadata:
  name: velero-service
  namespace: velero
spec:
  selector:
    app: velero
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: azure
  objectStorage:
    bucket: velero-backups
  config:
    resourceGroup: bookstore-rg
    storageAccount: bookstorevelerobckpgp7
  credential:
    name: cloud-credentials
    key: cloud
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-postgres-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"  # Runs at 2 AM UTC daily
  template:
    includedNamespaces:
      - default
    labelSelector:
      matchLabels:
        app: postgres